# Generated by Django 4.2.5 on 2023-09-23 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import image_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=image_api.models.path_and_rename)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=64)),
                ('originalLink', models.BooleanField(default=False)),
                ('expiringLink', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_api.tier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_api.tier')),
            ],
        ),
        migrations.CreateModel(
            name='ImageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default=image_api.models.generate_link, max_length=128)),
                ('expiration_time', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('height', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='image_api.imagesize')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_api.image')),
            ],
        ),
        migrations.CreateModel(
            name='ImageContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_api.imagecontainer'),
        ),
    ]
