# Generated by Django 4.2.5 on 2023-09-24 08:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLinkExpiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_time', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagelink',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='imagelink',
            name='expiration_time',
        ),
        migrations.AddField(
            model_name='imagelink',
            name='expiration',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_api.imagelinkexpiration'),
        ),
    ]
