# Generated by Django 4.2.5 on 2023-09-24 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0002_imagelinkexpiration_remove_imagelink_created_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagelink',
            name='expiration',
        ),
        migrations.AddField(
            model_name='imagelink',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='imagelink',
            name='expiration_time',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ImageLinkExpiration',
        ),
    ]
